- name: useradd 
  ansible.builtin.import_role:
    name: common
    tasks-from: app-setup

- name: java 
  ansible.builtin.import_role:
    name: common
    tasks_from: java

- name: mysql
  ansible.builtin.import_role:
    name: common
    tasks_from: mysql-setup

- name: restart and enable
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd