- name: app-setup
  ansible.builtin.import_roles:
    name: cart
    tasks_from: app-setup

- name: nodejs
  ansible.builtin.import_roles:
    name: common
    tasks_from: nodejs

- name: mongodb
  ansible.builtin.import_roles:
    name: common
    tasks_from: mongodb-setup

- name: system service
  ansible.builtin.import_roles:
    name: common
    tasks_from: systemd