- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: nodejs
  ansible.builtin.impoort_role:
    name: common
    tasks_from: nodejs

- name: mongodb-setup
  ansible.builtin.import_tasks:
    name: common
    tasks_from: mongodb-setup

- name: systemd
  ansible.builtin.import_tasks:
    name: common
    tasks_from: systemd
